FROM golang:1.22 as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server ./server
FROM gcr.io/distroless/base-debian12
WORKDIR /
COPY --from=builder /app/server /server
EXPOSE 50051
USER 65532:65532
ENTRYPOINT ["/server"]
